# Generated by Django 3.0.8 on 2023-01-02 10:35

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssortmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='AssortmentQualityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории по качеству продукции')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='name')),
            ],
            options={
                'verbose_name': 'Quality of category',
                'verbose_name_plural': 'Quality of categories',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Локация')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='name')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='TransactionTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Location', verbose_name='Куда (место)')),
                ('qty_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.AssortmentQualityCategory', verbose_name='Куда (качество)')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Причина перемещения')),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Location', verbose_name='Откуда (место)')),
                ('qty_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.AssortmentQualityCategory', verbose_name='Откуда (качество)')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Точное место')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='name')),
                ('image', models.ImageField(default='default.jpg', upload_to='photos_parts', verbose_name='Фотография')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.AssortmentCategory', verbose_name='Категория')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Location', verbose_name='Место хранения')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
            },
        ),
    ]
