# Generated by Django 3.0.8 on 2023-01-02 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Количество в системе')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Stock', verbose_name='Название')),
                ('type_quality_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.AssortmentQualityCategory', verbose_name='Название')),
            ],
        ),
    ]
