# Generated by Django 4.1.5 on 2023-01-26 15:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='number'),
        ),
    ]
