# Generated by Django 3.0.8 on 2023-01-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_quantityproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionfrom',
            name='location_from',
        ),
        migrations.RemoveField(
            model_name='transactionfrom',
            name='qty_from',
        ),
        migrations.RemoveField(
            model_name='transactionto',
            name='location_to',
        ),
        migrations.RemoveField(
            model_name='transactionto',
            name='qty_to',
        ),
        migrations.DeleteModel(
            name='QuantityProducts',
        ),
        migrations.DeleteModel(
            name='TransactionFrom',
        ),
        migrations.DeleteModel(
            name='TransactionTo',
        ),
    ]
