# Generated by Django 3.0.8 on 2023-01-14 09:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20230114_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='hjf', editable=False, populate_from='name'),
        ),
    ]
