# Generated by Django 3.0.8 on 2023-01-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20230102_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Куда/Откуда')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Куда/Откуда')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Количество')),
                ('reason', models.TextField(max_length=2000, verbose_name='Причина перемещения')),
                ('direction', models.ManyToManyField(to='mainapp.Direction', verbose_name='Откуда/Куда')),
                ('location', models.ManyToManyField(to='mainapp.Location', verbose_name='Перемещение (место)')),
                ('name', models.ManyToManyField(to='mainapp.Stock', verbose_name='Название')),
                ('quality', models.ManyToManyField(to='mainapp.AssortmentQualityCategory', verbose_name='Качество продукции')),
                ('status', models.ManyToManyField(to='mainapp.Status', verbose_name='Название')),
            ],
        ),
    ]
