# Generated by Django 4.1.5 on 2023-01-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_productlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductLog',
        ),
    ]
