# Generated by Django 3.0.8 on 2023-01-14 09:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_transaction_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
    ]
