# Generated by Django 3.0.8 on 2023-01-03 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Количество')),
                ('reason', models.TextField(max_length=2000, verbose_name='Причина перемещения')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Direction', verbose_name='Откуда/Куда')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Location', verbose_name='Перемещение (место)')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Stock', verbose_name='Название')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.AssortmentQualityCategory', verbose_name='Качество продукции')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Status', verbose_name='Название')),
            ],
        ),
    ]
