# Generated by Django 3.0.8 on 2023-01-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Количество'),
        ),
    ]
