# Generated by Django 4.1.6 on 2023-02-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
