# Generated by Django 3.0.8 on 2023-01-03 13:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='null', editable=True, populate_from='name'),
        ),
    ]
