# Generated by Django 3.0.8 on 2023-01-04 14:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20230103_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
    ]
