# Generated by Django 3.0.8 on 2023-01-05 14:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20230104_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='name'),
        ),
    ]
